### ISSUE TITLE
Additional Documentation or Examples

### ISSUE THREAD

**Issue by jdcauley** [markzero/wp-on-routes#1]
Hey,

I'm a little confused on how to get this thing working.

When I navigate to my route I'm not getting anything.

What am I doing wrong?

```
<?php

require_once('../../../wp-on-routes-master/lib/routes.php');

$routing = \WoR\Main::get_instance();

$routing->add_routes(
  array(
    'get' => array(
      'path' => '/foo/bar',
      'body' => 'Hello Buz!',
      'headers' => array(
        'Content-Type' => 'text/html; charset=UTF-8',
        'exclude' => array(
          'x-powered-by', 'x-pingback'
        )
      )
    )
  )
);

if (!class_exists('\WoR\Main')) {
  return;
}
```

update: I tried it on an un-edited WP theme and must be missing something because nothing works at all

**Comment by mk0y** [comment]
You can't just require specific file, this is plugin and should be used as plugin.
When you require `routes.php` you don't achieve anything since it's only part of package. Just clone or unzip this plugin into plugins dir and activate it.

**Comment by jdcauley** [comment]
I did that as well and didn't do the require and when navigating to the created route I just got a 404

**Comment by mk0y** [comment]
Here's the code I used: https://db.tt/u1e7AWWl

You can check here the result: http://wor.devcanyon.com/foo/bar

It is normal twentyfourteen theme there, i put it inside `functions.php`, on lines below some `$content_width` variable definition, so almost at the top.
